spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.h2.Driver   # общий драйвер (будет переопределен для prod)
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"  # кастомный формат даты в логах
server:
  port: 8081
app:
  welcome-message: "Welcome to Spring blog, yo!"  # наше кастомное сообщение
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem